AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  SuggestExtensions: false
  NewCops: enable
Layout/EndOfLine:
  EnforcedStyle: lf
Lint/MissingSuper:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/AbcSize:
  Max: 65
Metrics/BlockLength:
  Max: 30
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 180
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/ParameterLists:
  Max: 10
Layout/ParameterAlignment:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
