# SPDX-FileCopyrightText: Copyright (c) 2019 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  SuggestExtensions: false
  NewCops: enable
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
Layout/EndOfLine:
  EnforcedStyle: lf
Lint/MissingSuper:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Minitest/MultipleAssertions:
  Max: 5
Metrics/AbcSize:
  Max: 65
Metrics/BlockLength:
  Max: 30
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 180
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/ParameterLists:
  Max: 10
Layout/ParameterAlignment:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
require: []
