# SPDX-FileCopyrightText: Copyright (c) 2019 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/ruby
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |-
  sudo chown -R "$(whoami)" /usr/local/rvm
  pdd -f /dev/null
  bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  pre: false
  script: |-
    bundle exec rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" veils.gemspec
    git add veils.gemspec
    git commit -m "Version set to ${tag}"
    gem build veils.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle install
    bundle exec rake
